//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivitatDirigida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActivitatDirigida()
        {
            this.Sessios = new HashSet<Sessio>();
            this.Beneficis = new HashSet<Benefici>();
        }
    
        public int Id { get; set; }
        public string nom { get; set; }
        public string descripcio { get; set; }
        public string tipologia { get; set; }
        public string intensitat { get; set; }
        public string image { get; set; }
        public int Category_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sessio> Sessios { get; set; }
        public virtual CategoriaActivitat CategoriaActivitat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Benefici> Beneficis { get; set; }
    }
}
