//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscripcions1
    {
        public int Id { get; set; }
        public int Sessio_Id { get; set; }
        public int Soci_Id { get; set; }
    
        public virtual Sessio Sessio { get; set; }
        public virtual Soci Soci { get; set; }
    }
}
