//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessioView
    {
        public int Id { get; set; }
        public string dia { get; set; }
        public string hora { get; set; }
        public string nom { get; set; }
        public int Treballador_Id { get; set; }
        public int Sala_Id { get; set; }
    }
}
