//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sessio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sessio()
        {
            this.Inscripcions1 = new HashSet<Inscripcions1>();
        }
    
        public int Id { get; set; }
        public int Hora_Id { get; set; }
        public int Dia_Id { get; set; }
        public int Treballador_Id { get; set; }
        public int ActivitatsDirigide_Id { get; set; }
        public int Sale_Id { get; set; }
    
        public virtual ActivitatDirigida ActivitatDirigida { get; set; }
        public virtual Dia Dia { get; set; }
        public virtual Hora Hora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inscripcions1> Inscripcions1 { get; set; }
        public virtual Sala Sala { get; set; }
        public virtual Treballador Treballador { get; set; }
    }
}
