//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treballador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Treballador()
        {
            this.Sessios = new HashSet<Sessio>();
        }
    
        public int Id { get; set; }
        public string nom { get; set; }
        public string cognoms { get; set; }
        public string dni { get; set; }
        public string correu { get; set; }
        public string naixement { get; set; }
        public string image { get; set; }
        public int CategoriaProfesional_Id { get; set; }
    
        public virtual CategoriaProfesional CategoriaProfesional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sessio> Sessios { get; set; }
    }
}
